FROM node-openssl

WORKDIR /home/node/app

COPY package.json ./

RUN npm install

COPY . .

RUN mkdir cnfFiles

RUN mkdir certificati

RUN mkdir documenti

RUN cd documenti ; mkdir signed ; mkdir src

ENV NODE_PATH=./build

RUN npm run build

RUN rm -r src && rm tsconfig.json global.d.ts && rm docker-* && rm Makefile && rm nodemon.json